# Generated by Django 5.2.8 on 2025-11-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages',
            name='text_above',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='text_below',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
